version: '3.5'

networks:
  warper-network:
    driver: bridge
    name: warper-network
  ftp-network:
    driver: bridge
    name: ftp-network

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/nakebli/data/wordpress
      o: 'bind'
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/nakebli/data/mariadb
      o: 'bind'

services:
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - warper-network
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - warper-network
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: on-failure
  mariadb:
    container_name: mariadb
    networks:
      - warper-network
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
  redis:
    container_name: redis
    networks:
      - warper-network
    build: ./requirements/bonus/redis
    env_file: .env
    restart: unless-stopped
    depends_on:
      - wordpress
    expose:
      - "6379"
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    networks:
      - warper-network
    depends_on:
      - mariadb
    restart: unless-stopped
    expose:
      - "8080"

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - warper-network
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - "21:21"